# Generated by Django 4.2.2 on 2023-07-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_appliedsubmission_post'),
        ('users', '0002_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_submitted_form',
            field=models.ManyToManyField(blank=True, to='blog.post'),
        ),
    ]
