# Generated by Django 4.2.2 on 2023-07-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_appliedsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unique_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
