# Generated by Django 4.2.2 on 2023-07-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_unique_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedsubmission',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
            preserve_default=False,
        ),
    ]
